# Generated by Django 4.2.6 on 2023-12-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="课程ID"
                    ),
                ),
                ("course_name", models.CharField()),
                ("teacher_id", models.IntegerField(verbose_name="老师ID")),
                ("credits", models.IntegerField()),
                ("requirements", models.CharField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(verbose_name="课程ID")),
                ("student_id", models.IntegerField(verbose_name="学生ID")),
                ("attend_point", models.SmallIntegerField(blank=True, default=None)),
                ("exam_point", models.SmallIntegerField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "stu_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="学生ID"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", null=True, verbose_name="学生邮箱"
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "tea_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="老师ID"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", null=True, verbose_name="老师邮箱"
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="用户ID"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", null=True, verbose_name="用户邮箱"
                    ),
                ),
                (
                    "tag",
                    models.SmallIntegerField(
                        choices=[(0, "管理员"), (1, "老师"), (2, "学生")], verbose_name="身份选择"
                    ),
                ),
                ("password", models.CharField(verbose_name="密码")),
                ("name", models.CharField(verbose_name="姓名")),
            ],
        ),
    ]
