# Generated by Django 4.2.6 on 2023-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apptest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="用户ID"
            ),
        ),
    ]
